# typed: false
# frozen_string_literal: true

# Auto-generated by .github/workflows/homebrew-bump.yaml — do not
# hand-edit in the tap repo. Source of truth lives in
# drewcarlson/bwx-cli at packaging/homebrew/bwx-cli.rb.
class BwxCli < Formula
  desc "Unofficial Bitwarden CLI with first-class macOS support"
  homepage "https://github.com/drewcarlson/bwx-cli"
  version "2.3.1"
  license "MIT"

  # Linux needs pinentry for the master-password UI; macOS uses the
  # bundled osascript dialog so it's optional there.
  on_linux do
    depends_on "pinentry"
  end

  on_macos do
    on_arm do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "23de6cdf331c6052b0df52b5adac582a08519d7dd7e9014b76cc9ab7c35e4f96"
    end
    on_intel do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "0cea2bb9da6f77c3ab966574bce84e412802d3aab91bb6e5a1542fcdd836c0b6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "5929fd4e7c07f7fe547cb1e7b1f8d1f9bbe8b03418e2da93183c17a8e3292329"
    end
    on_intel do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "19f57ebf16e46f268f3f596dde04c5c26179511edcc6f01ded80eb6ab911de55"
    end
  end

  def install
    bin.install "bwx", "bwx-agent"
    bash_completion.install "completion/bash" => "bwx"
    zsh_completion.install "completion/zsh" => "_bwx"
    fish_completion.install "completion/fish" => "bwx.fish"
    doc.install "README.md", "CHANGELOG.md"
  end

  test do
    assert_match(/\A(bwx )?\d+\.\d+\.\d+/, shell_output("#{bin}/bwx --version"))
    assert_match "Touch ID", shell_output("#{bin}/bwx help touchid")
  end
end
