# typed: false
# frozen_string_literal: true

# Auto-generated by .github/workflows/homebrew-bump.yaml — do not
# hand-edit in the tap repo. Source of truth lives in
# drewcarlson/bwx-cli at packaging/homebrew/bwx-cli.rb.
class BwxCli < Formula
  desc "Unofficial Bitwarden CLI with first-class macOS support"
  homepage "https://github.com/drewcarlson/bwx-cli"
  version "2.2.1"
  license "MIT"

  # Linux needs pinentry for the master-password UI; macOS uses the
  # bundled osascript dialog so it's optional there.
  on_linux do
    depends_on "pinentry"
  end

  on_macos do
    on_arm do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "8ecda39b756de6dad8a67d00e51287517faae8d6c7f7fcba625cd94a5cd979cd"
    end
    on_intel do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "84ba0e30e9e486206cd4e269b22b2f5f112286da23b399b0c33cb19331366bec"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4562864dce46d262bc4f20f9af25e420db2b781d8b5b1ca3307a93dff9a32649"
    end
    on_intel do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "c9a1783568b578f539c132de7c4d363f0fd687f62187da1dbf0272b174ec567e"
    end
  end

  def install
    bin.install "bwx", "bwx-agent"
    bash_completion.install "completion/bash" => "bwx"
    zsh_completion.install "completion/zsh" => "_bwx"
    fish_completion.install "completion/fish" => "bwx.fish"
    doc.install "README.md", "CHANGELOG.md"
  end

  test do
    assert_match(/\A(bwx )?\d+\.\d+\.\d+/, shell_output("#{bin}/bwx --version"))
    assert_match "Touch ID", shell_output("#{bin}/bwx help touchid")
  end
end
