# typed: false
# frozen_string_literal: true

# Auto-generated by .github/workflows/homebrew-bump.yaml — do not
# hand-edit in the tap repo. Source of truth lives in
# drewcarlson/bwx-cli at packaging/homebrew/bwx-cli.rb.
class BwxCli < Formula
  desc "Unofficial Bitwarden CLI with first-class macOS support"
  homepage "https://github.com/drewcarlson/bwx-cli"
  version "2.1.0"
  license "MIT"

  # Linux needs pinentry for the master-password UI; macOS uses the
  # bundled osascript dialog so it's optional there.
  on_linux do
    depends_on "pinentry"
  end

  on_macos do
    on_arm do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "2b493d89c6f058a62c6c273613ceab242646534f9199abd32f50676e74a2dcf7"
    end
    on_intel do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "4f636820e8aa785e71329181483d1b6418dbd429826282279affbb385e110ffc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "28b3fec395af893109643ff97cf442b8d25dab035c8d41ad68e878faedb105dc"
    end
    on_intel do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "da49fef544abc1459a69952044ceb561c5da6959b5b200f119d21c14134c5938"
    end
  end

  def install
    bin.install "bwx", "bwx-agent"
    bash_completion.install "completion/bash" => "bwx"
    zsh_completion.install "completion/zsh" => "_bwx"
    fish_completion.install "completion/fish" => "bwx.fish"
    doc.install "README.md", "CHANGELOG.md"
  end

  test do
    assert_match(/\A(bwx )?\d+\.\d+\.\d+/, shell_output("#{bin}/bwx --version"))
    assert_match "Touch ID", shell_output("#{bin}/bwx help touchid")
  end
end
